using System.Collections.Generic;
using api.Dtos.Stock;

namespace StockReview.Services
{
    // Mid-cap / second-tier tickers appended to the live-market search
    // universe (PopularStocks.All = LargeCap + MidCap). Same rules as the
    // large-cap file: symbols are unique across both lists, and FMP's free
    // quote endpoint (used by POST /api/stock/from-live) validates whatever
    // the user picks, so a stale name here is cosmetic, never harmful.
    public static class PopularStocksMidCap
    {
        public static readonly IReadOnlyList<FMPStockSearchResult> All =
            new List<FMPStockSearchResult>
            {
                // Technology & software
                new() { symbol = "ZM", name = "Zoom Video Communications, Inc.", exchange = "NASDAQ" },
                new() { symbol = "WDAY", name = "Workday, Inc.", exchange = "NASDAQ" },
                new() { symbol = "TEAM", name = "Atlassian Corporation", exchange = "NASDAQ" },
                new() { symbol = "S", name = "SentinelOne, Inc.", exchange = "NYSE" },
                new() { symbol = "OKTA", name = "Okta, Inc.", exchange = "NASDAQ" },
                new() { symbol = "TWLO", name = "Twilio Inc.", exchange = "NYSE" },
                new() { symbol = "RBLX", name = "Roblox Corporation", exchange = "NYSE" },
                new() { symbol = "U", name = "Unity Software Inc.", exchange = "NYSE" },
                new() { symbol = "GTLB", name = "GitLab Inc.", exchange = "NASDAQ" },
                new() { symbol = "PATH", name = "UiPath Inc.", exchange = "NYSE" },
                new() { symbol = "BILL", name = "BILL Holdings, Inc.", exchange = "NYSE" },
                new() { symbol = "PAYC", name = "Paycom Software, Inc.", exchange = "NYSE" },
                new() { symbol = "PAYX", name = "Paychex, Inc.", exchange = "NASDAQ" },
                new() { symbol = "MDB", name = "MongoDB, Inc.", exchange = "NASDAQ" },
                new() { symbol = "ESTC", name = "Elastic N.V.", exchange = "NYSE" },
                new() { symbol = "GDDY", name = "GoDaddy Inc.", exchange = "NYSE" },
                new() { symbol = "VRSN", name = "VeriSign, Inc.", exchange = "NASDAQ" },
                new() { symbol = "FFIV", name = "F5, Inc.", exchange = "NASDAQ" },
                new() { symbol = "ANET", name = "Arista Networks, Inc.", exchange = "NYSE" },
                new() { symbol = "NTAP", name = "NetApp, Inc.", exchange = "NASDAQ" },
                new() { symbol = "DELL", name = "Dell Technologies Inc.", exchange = "NYSE" },
                new() { symbol = "HPQ", name = "HP Inc.", exchange = "NYSE" },
                new() { symbol = "HPE", name = "Hewlett Packard Enterprise Company", exchange = "NYSE" },
                new() { symbol = "SMCI", name = "Super Micro Computer, Inc.", exchange = "NASDAQ" },
                new() { symbol = "STX", name = "Seagate Technology Holdings plc", exchange = "NASDAQ" },
                new() { symbol = "WDC", name = "Western Digital Corporation", exchange = "NASDAQ" },
                new() { symbol = "LOGI", name = "Logitech International S.A.", exchange = "NASDAQ" },
                new() { symbol = "ZBRA", name = "Zebra Technologies Corporation", exchange = "NASDAQ" },
                new() { symbol = "JNPR", name = "Juniper Networks, Inc.", exchange = "NYSE" },
                new() { symbol = "CDW", name = "CDW Corporation", exchange = "NASDAQ" },
                new() { symbol = "HUBS", name = "HubSpot, Inc.", exchange = "NYSE" },
                new() { symbol = "RBRK", name = "Rubrik, Inc.", exchange = "NYSE" },
                // Consumer internet
                new() { symbol = "ROKU", name = "Roku, Inc.", exchange = "NASDAQ" },
                new() { symbol = "PINS", name = "Pinterest, Inc.", exchange = "NYSE" },
                new() { symbol = "SNAP", name = "Snap Inc.", exchange = "NYSE" },
                new() { symbol = "MTCH", name = "Match Group, Inc.", exchange = "NASDAQ" },
                new() { symbol = "BMBL", name = "Bumble Inc.", exchange = "NASDAQ" },
                new() { symbol = "YELP", name = "Yelp Inc.", exchange = "NYSE" },
                new() { symbol = "TRIP", name = "Tripadvisor, Inc.", exchange = "NASDAQ" },
                new() { symbol = "EXPE", name = "Expedia Group, Inc.", exchange = "NASDAQ" },
                new() { symbol = "TCOM", name = "Trip.com Group Limited", exchange = "NASDAQ" },
                new() { symbol = "EPAM", name = "EPAM Systems, Inc.", exchange = "NYSE" },
                new() { symbol = "GLOB", name = "Globant S.A.", exchange = "NYSE" },
                new() { symbol = "INFY", name = "Infosys Limited", exchange = "NYSE" },
                new() { symbol = "WIT", name = "Wipro Limited", exchange = "NYSE" },
                new() { symbol = "NU", name = "Nu Holdings Ltd.", exchange = "NYSE" },
                new() { symbol = "AFRM", name = "Affirm Holdings, Inc.", exchange = "NASDAQ" },
                new() { symbol = "UPST", name = "Upstart Holdings, Inc.", exchange = "NASDAQ" },
                new() { symbol = "STNE", name = "StoneCo Ltd.", exchange = "NASDAQ" },
                new() { symbol = "MSTR", name = "MicroStrategy Incorporated", exchange = "NASDAQ" },
                new() { symbol = "IREN", name = "IREN Limited", exchange = "NASDAQ" },
                new() { symbol = "MARA", name = "Marathon Digital Holdings, Inc.", exchange = "NASDAQ" },
                new() { symbol = "RIOT", name = "Riot Platforms, Inc.", exchange = "NASDAQ" },
                new() { symbol = "PLUG", name = "Plug Power Inc.", exchange = "NASDAQ" },
                new() { symbol = "JOBY", name = "Joby Aviation, Inc.", exchange = "NYSE" },
                new() { symbol = "ACHR", name = "Archer Aviation Inc.", exchange = "NYSE" },
                new() { symbol = "RKLB", name = "Rocket Lab USA, Inc.", exchange = "NASDAQ" },
                new() { symbol = "ASTS", name = "AST SpaceMobile, Inc.", exchange = "NASDAQ" },
                new() { symbol = "SOUN", name = "SoundHound AI, Inc.", exchange = "NASDAQ" },
                new() { symbol = "CRCL", name = "Circle Internet Group, Inc.", exchange = "NYSE" },
                new() { symbol = "BBAI", name = "BigBear.ai Holdings, Inc.", exchange = "NYSE" },
                // Healthcare
                new() { symbol = "DXCM", name = "DexCom, Inc.", exchange = "NASDAQ" },
                new() { symbol = "PODD", name = "Insulet Corporation", exchange = "NASDAQ" },
                new() { symbol = "ALGN", name = "Align Technology, Inc.", exchange = "NASDAQ" },
                new() { symbol = "IDXX", name = "IDEXX Laboratories, Inc.", exchange = "NASDAQ" },
                new() { symbol = "WAT", name = "Waters Corporation", exchange = "NYSE" },
                new() { symbol = "MASI", name = "Masimo Corporation", exchange = "NASDAQ" },
                new() { symbol = "PEN", name = "Penumbra, Inc.", exchange = "NYSE" },
                new() { symbol = "HAE", name = "Haemonetics Corporation", exchange = "NYSE" },
                new() { symbol = "NVST", name = "Envista Holdings Corporation", exchange = "NYSE" },
                new() { symbol = "STE", name = "STERIS plc", exchange = "NYSE" },
                new() { symbol = "RDNT", name = "RadNet, Inc.", exchange = "NASDAQ" },
                new() { symbol = "DGX", name = "Quest Diagnostics Incorporated", exchange = "NYSE" },
                new() { symbol = "LH", name = "Laboratory Corporation of America Holdings", exchange = "NYSE" },
                new() { symbol = "DVA", name = "DaVita Inc.", exchange = "NYSE" },
                new() { symbol = "UHS", name = "Universal Health Services, Inc.", exchange = "NYSE" },
                new() { symbol = "THC", name = "Tenet Healthcare Corporation", exchange = "NYSE" },
                new() { symbol = "HCA", name = "HCA Healthcare, Inc.", exchange = "NYSE" },
                new() { symbol = "CHE", name = "Chemed Corporation", exchange = "NYSE" },
                new() { symbol = "EHC", name = "Encompass Health Corporation", exchange = "NYSE" },
                new() { symbol = "ENSG", name = "The Ensign Group, Inc.", exchange = "NASDAQ" },
                new() { symbol = "CAH", name = "Cardinal Health, Inc.", exchange = "NYSE" },
                new() { symbol = "MCK", name = "McKesson Corporation", exchange = "NYSE" },
                new() { symbol = "COR", name = "Cencora, Inc.", exchange = "NYSE" },
                new() { symbol = "PDCO", name = "Patterson Companies, Inc.", exchange = "NASDAQ" },
                new() { symbol = "HSIC", name = "Henry Schein, Inc.", exchange = "NASDAQ" },
                new() { symbol = "BAX", name = "Baxter International Inc.", exchange = "NYSE" },
                new() { symbol = "BIIB", name = "Biogen Inc.", exchange = "NASDAQ" },
                new() { symbol = "ILMN", name = "Illumina, Inc.", exchange = "NASDAQ" },
                new() { symbol = "EXAS", name = "Exact Sciences Corporation", exchange = "NASDAQ" },
                new() { symbol = "GH", name = "Guardant Health, Inc.", exchange = "NASDAQ" },
                new() { symbol = "NTLA", name = "Intellia Therapeutics, Inc.", exchange = "NASDAQ" },
                new() { symbol = "BEAM", name = "Beam Therapeutics Inc.", exchange = "NASDAQ" },
                new() { symbol = "CRSP", name = "CRISPR Therapeutics AG", exchange = "NASDAQ" },
                new() { symbol = "ARWR", name = "Arrowhead Pharmaceuticals, Inc.", exchange = "NASDAQ" },
                new() { symbol = "IONS", name = "Ionis Pharmaceuticals, Inc.", exchange = "NASDAQ" },
                new() { symbol = "ALNY", name = "Alnylam Pharmaceuticals, Inc.", exchange = "NASDAQ" },
                new() { symbol = "INCY", name = "Incyte Corporation", exchange = "NASDAQ" },
                new() { symbol = "UTHR", name = "United Therapeutics Corporation", exchange = "NASDAQ" },
                new() { symbol = "BMRN", name = "BioMarin Pharmaceutical Inc.", exchange = "NASDAQ" },
                new() { symbol = "NBIX", name = "Neurocrine Biosciences, Inc.", exchange = "NASDAQ" },
                new() { symbol = "SRPT", name = "Sarepta Therapeutics, Inc.", exchange = "NASDAQ" },
                new() { symbol = "PCVX", name = "Vaxcyte, Inc.", exchange = "NASDAQ" },
                new() { symbol = "AZN", name = "AstraZeneca PLC", exchange = "NASDAQ" },
                new() { symbol = "NVS", name = "Novartis AG", exchange = "NYSE" },
                new() { symbol = "SNY", name = "Sanofi", exchange = "NASDAQ" },
                new() { symbol = "GSK", name = "GSK plc", exchange = "NYSE" },
                new() { symbol = "RDY", name = "Dr. Reddy's Laboratories Limited", exchange = "NYSE" },
                new() { symbol = "VEEV", name = "Veeva Systems Inc.", exchange = "NYSE" },
                new() { symbol = "TDOC", name = "Teladoc Health, Inc.", exchange = "NYSE" },
                new() { symbol = "EVH", name = "Evolent Health, Inc.", exchange = "NYSE" },
                new() { symbol = "DNA", name = "Ginkgo Bioworks Holdings, Inc.", exchange = "NYSE" },
                new() { symbol = "RXRX", name = "Recursion Pharmaceuticals, Inc.", exchange = "NASDAQ" },
                // Restaurants & consumer staples
                new() { symbol = "SHAK", name = "Shake Shack Inc.", exchange = "NYSE" },
                new() { symbol = "WING", name = "Wingstop Inc.", exchange = "NASDAQ" },
                new() { symbol = "CAVA", name = "CAVA Group, Inc.", exchange = "NYSE" },
                new() { symbol = "JACK", name = "Jack in the Box Inc.", exchange = "NASDAQ" },
                new() { symbol = "DIN", name = "Dine Brands Global, Inc.", exchange = "NYSE" },
                new() { symbol = "QSR", name = "Restaurant Brands International Inc.", exchange = "NYSE" },
                new() { symbol = "YUMC", name = "Yum China Holdings, Inc.", exchange = "NYSE" },
                new() { symbol = "WEN", name = "The Wendy's Company", exchange = "NASDAQ" },
                new() { symbol = "BROS", name = "Dutch Bros Inc.", exchange = "NYSE" },
                new() { symbol = "PLAY", name = "Dave & Buster's Entertainment, Inc.", exchange = "NASDAQ" },
                new() { symbol = "LKNCY", name = "Luckin Coffee Inc.", exchange = "NASDAQ" },
                new() { symbol = "DNUT", name = "Krispy Kreme, Inc.", exchange = "NASDAQ" },
                new() { symbol = "LW", name = "Lamb Weston Holdings, Inc.", exchange = "NYSE" },
                new() { symbol = "POST", name = "Post Holdings, Inc.", exchange = "NYSE" },
                new() { symbol = "MKC", name = "McCormick & Company, Incorporated", exchange = "NYSE" },
                new() { symbol = "CAG", name = "Conagra Brands, Inc.", exchange = "NYSE" },
                new() { symbol = "CPB", name = "The Campbell's Company", exchange = "NYSE" },
                new() { symbol = "HRL", name = "Hormel Foods Corporation", exchange = "NYSE" },
                new() { symbol = "SJM", name = "The J.M. Smucker Company", exchange = "NYSE" },
                new() { symbol = "TSN", name = "Tyson Foods, Inc.", exchange = "NYSE" },
                new() { symbol = "PPC", name = "Pilgrim's Pride Corporation", exchange = "NASDAQ" },
                new() { symbol = "DAR", name = "Darling Ingredients Inc.", exchange = "NYSE" },
                new() { symbol = "BG", name = "Bunge Global SA", exchange = "NYSE" },
                new() { symbol = "ADM", name = "Archer-Daniels-Midland Company", exchange = "NYSE" },
                // Retail & apparel
                new() { symbol = "TSCO", name = "Tractor Supply Company", exchange = "NASDAQ" },
                new() { symbol = "DKS", name = "Dick's Sporting Goods, Inc.", exchange = "NYSE" },
                new() { symbol = "ASO", name = "Academy Sports and Outdoors, Inc.", exchange = "NASDAQ" },
                new() { symbol = "BBY", name = "Best Buy Co., Inc.", exchange = "NYSE" },
                new() { symbol = "GPS", name = "The Gap, Inc.", exchange = "NYSE" },
                new() { symbol = "ANF", name = "Abercrombie & Fitch Co.", exchange = "NYSE" },
                new() { symbol = "AEO", name = "American Eagle Outfitters, Inc.", exchange = "NYSE" },
                new() { symbol = "URBN", name = "Urban Outfitters, Inc.", exchange = "NASDAQ" },
                new() { symbol = "LULU", name = "Lululemon Athletica Inc.", exchange = "NASDAQ" },
                new() { symbol = "ONON", name = "On Holding AG", exchange = "NYSE" },
                new() { symbol = "CROX", name = "Crocs, Inc.", exchange = "NASDAQ" },
                new() { symbol = "SKX", name = "Skechers U.S.A., Inc.", exchange = "NYSE" },
                new() { symbol = "DECK", name = "Deckers Outdoor Corporation", exchange = "NYSE" },
                new() { symbol = "BKE", name = "The Buckle, Inc.", exchange = "NYSE" },
                new() { symbol = "FL", name = "Foot Locker, Inc.", exchange = "NYSE" },
                new() { symbol = "CAL", name = "Caleres, Inc.", exchange = "NYSE" },
                new() { symbol = "RH", name = "RH", exchange = "NYSE" },
                new() { symbol = "WSM", name = "Williams-Sonoma, Inc.", exchange = "NYSE" },
                new() { symbol = "FND", name = "Floor & Decor Holdings, Inc.", exchange = "NYSE" },
                // Homebuilders
                new() { symbol = "TOL", name = "Toll Brothers, Inc.", exchange = "NYSE" },
                new() { symbol = "LEN", name = "Lennar Corporation", exchange = "NYSE" },
                new() { symbol = "PHM", name = "PulteGroup, Inc.", exchange = "NYSE" },
                new() { symbol = "DHI", name = "D.R. Horton, Inc.", exchange = "NYSE" },
                new() { symbol = "NVR", name = "NVR, Inc.", exchange = "NYSE" },
                new() { symbol = "MTH", name = "Meritage Homes Corporation", exchange = "NYSE" },
                new() { symbol = "KBH", name = "KB Home", exchange = "NYSE" },
                // Gaming, travel & leisure
                new() { symbol = "WYNN", name = "Wynn Resorts, Limited", exchange = "NASDAQ" },
                new() { symbol = "LVS", name = "Las Vegas Sands Corp.", exchange = "NYSE" },
                new() { symbol = "MGM", name = "MGM Resorts International", exchange = "NYSE" },
                new() { symbol = "CZR", name = "Caesars Entertainment, Inc.", exchange = "NASDAQ" },
                new() { symbol = "PENN", name = "PENN Entertainment, Inc.", exchange = "NASDAQ" },
                new() { symbol = "CHDN", name = "Churchill Downs Incorporated", exchange = "NASDAQ" },
                new() { symbol = "BYD", name = "Boyd Gaming Corporation", exchange = "NYSE" },
                new() { symbol = "DKNG", name = "DraftKings Inc.", exchange = "NASDAQ" },
                new() { symbol = "PLNT", name = "Planet Fitness, Inc.", exchange = "NYSE" },
                new() { symbol = "PTON", name = "Peloton Interactive, Inc.", exchange = "NASDAQ" },
                new() { symbol = "NCLH", name = "Norwegian Cruise Line Holdings Ltd.", exchange = "NYSE" },
                new() { symbol = "CCL", name = "Carnival Corporation & plc", exchange = "NYSE" },
                new() { symbol = "RCL", name = "Royal Caribbean Cruises Ltd.", exchange = "NYSE" },
                new() { symbol = "HLT", name = "Hilton Worldwide Holdings Inc.", exchange = "NYSE" },
                new() { symbol = "MAR", name = "Marriott International, Inc.", exchange = "NASDAQ" },
                new() { symbol = "IHG", name = "InterContinental Hotels Group plc", exchange = "NYSE" },
                new() { symbol = "CHH", name = "Choice Hotels International, Inc.", exchange = "NYSE" },
                new() { symbol = "HTHT", name = "H World Group Limited", exchange = "NASDAQ" },
                new() { symbol = "VIK", name = "Viking Holdings Ltd", exchange = "NYSE" },
                // Energy
                new() { symbol = "FANG", name = "Diamondback Energy, Inc.", exchange = "NASDAQ" },
                new() { symbol = "EOG", name = "EOG Resources, Inc.", exchange = "NYSE" },
                new() { symbol = "DVN", name = "Devon Energy Corporation", exchange = "NYSE" },
                new() { symbol = "MRO", name = "Marathon Oil Corporation", exchange = "NYSE" },
                new() { symbol = "APA", name = "APA Corporation", exchange = "NASDAQ" },
                new() { symbol = "HES", name = "Hess Corporation", exchange = "NYSE" },
                new() { symbol = "CTRA", name = "Coterra Energy Inc.", exchange = "NYSE" },
                new() { symbol = "SWN", name = "Southwestern Energy Company", exchange = "NYSE" },
                new() { symbol = "AR", name = "Antero Resources Corporation", exchange = "NYSE" },
                new() { symbol = "RRC", name = "Range Resources Corporation", exchange = "NYSE" },
                new() { symbol = "CHK", name = "Chesapeake Energy Corporation", exchange = "NASDAQ" },
                new() { symbol = "PR", name = "Permian Resources Corporation", exchange = "NYSE" },
                // Clean energy
                new() { symbol = "FSLR", name = "First Solar, Inc.", exchange = "NASDAQ" },
                new() { symbol = "ENPH", name = "Enphase Energy, Inc.", exchange = "NASDAQ" },
                new() { symbol = "SEDG", name = "SolarEdge Technologies, Inc.", exchange = "NASDAQ" },
                new() { symbol = "RUN", name = "Sunrun Inc.", exchange = "NASDAQ" },
                // Utilities
                new() { symbol = "NEE", name = "NextEra Energy, Inc.", exchange = "NYSE" },
                new() { symbol = "DUK", name = "Duke Energy Corporation", exchange = "NYSE" },
                new() { symbol = "SO", name = "The Southern Company", exchange = "NYSE" },
                new() { symbol = "D", name = "Dominion Energy, Inc.", exchange = "NYSE" },
                new() { symbol = "AEP", name = "American Electric Power Company, Inc.", exchange = "NASDAQ" },
                new() { symbol = "EXC", name = "Exelon Corporation", exchange = "NASDAQ" },
                new() { symbol = "XEL", name = "Xcel Energy Inc.", exchange = "NASDAQ" },
                new() { symbol = "EIX", name = "Edison International", exchange = "NYSE" },
                new() { symbol = "PEG", name = "Public Service Enterprise Group Incorporated", exchange = "NYSE" },
                new() { symbol = "ED", name = "Consolidated Edison, Inc.", exchange = "NYSE" },
                new() { symbol = "FE", name = "FirstEnergy Corp.", exchange = "NYSE" },
                new() { symbol = "PCG", name = "PG&E Corporation", exchange = "NYSE" },
                // Midstream
                new() { symbol = "ET", name = "Energy Transfer LP", exchange = "NYSE" },
                new() { symbol = "WMB", name = "The Williams Companies, Inc.", exchange = "NYSE" },
                new() { symbol = "KMI", name = "Kinder Morgan, Inc.", exchange = "NYSE" },
                new() { symbol = "PBA", name = "Pembina Pipeline Corporation", exchange = "NYSE" },
                new() { symbol = "TRP", name = "TC Energy Corporation", exchange = "NYSE" },
                new() { symbol = "ENB", name = "Enbridge Inc.", exchange = "NYSE" },
                new() { symbol = "OKE", name = "ONEOK, Inc.", exchange = "NYSE" },
                // Environmental services
                new() { symbol = "CLH", name = "Clean Harbors, Inc.", exchange = "NYSE" },
                new() { symbol = "WCN", name = "Waste Connections, Inc.", exchange = "NYSE" },
                new() { symbol = "RSG", name = "Republic Services, Inc.", exchange = "NYSE" },
                new() { symbol = "WM", name = "Waste Management, Inc.", exchange = "NYSE" },
                // Materials & miners
                new() { symbol = "MP", name = "MP Materials Corp.", exchange = "NYSE" },
                new() { symbol = "ALB", name = "Albemarle Corporation", exchange = "NYSE" },
                new() { symbol = "SQM", name = "Sociedad Química y Minera de Chile S.A.", exchange = "NYSE" },
                new() { symbol = "AEM", name = "Agnico Eagle Mines Limited", exchange = "NYSE" },
                new() { symbol = "GOLD", name = "Barrick Gold Corporation", exchange = "NYSE" },
                new() { symbol = "WPM", name = "Wheaton Precious Metals Corp.", exchange = "NYSE" },
                new() { symbol = "PAAS", name = "Pan American Silver Corp.", exchange = "NYSE" },
                new() { symbol = "HL", name = "Hecla Mining Company", exchange = "NYSE" },
                new() { symbol = "RGLD", name = "Royal Gold, Inc.", exchange = "NASDAQ" },
                // Banks & financials
                new() { symbol = "TFC", name = "Truist Financial Corporation", exchange = "NYSE" },
                new() { symbol = "STT", name = "State Street Corporation", exchange = "NYSE" },
                new() { symbol = "BK", name = "The Bank of New York Mellon Corporation", exchange = "NYSE" },
                new() { symbol = "NTRS", name = "Northern Trust Corporation", exchange = "NASDAQ" },
                new() { symbol = "RF", name = "Regions Financial Corporation", exchange = "NYSE" },
                new() { symbol = "KEY", name = "KeyCorp", exchange = "NYSE" },
                new() { symbol = "HBAN", name = "Huntington Bancshares Incorporated", exchange = "NASDAQ" },
                new() { symbol = "CMA", name = "Comerica Incorporated", exchange = "NYSE" },
                new() { symbol = "ZION", name = "Zions Bancorporation, National Association", exchange = "NASDAQ" },
                new() { symbol = "FITB", name = "Fifth Third Bancorp", exchange = "NASDAQ" },
                new() { symbol = "CFG", name = "Citizens Financial Group, Inc.", exchange = "NYSE" },
                new() { symbol = "SYF", name = "Synchrony Financial", exchange = "NYSE" },
                new() { symbol = "DFS", name = "Discover Financial Services", exchange = "NYSE" },
                new() { symbol = "OMF", name = "OneMain Holdings, Inc.", exchange = "NYSE" },
                new() { symbol = "SLM", name = "SLM Corporation", exchange = "NASDAQ" },
                new() { symbol = "PAGS", name = "PagSeguro Digital Ltd.", exchange = "NYSE" },
                new() { symbol = "XP", name = "XP Inc.", exchange = "NASDAQ" },
                new() { symbol = "ITUB", name = "Itaú Unibanco Holding S.A.", exchange = "NYSE" },
                new() { symbol = "BBD", name = "Banco Bradesco S.A.", exchange = "NYSE" },
                new() { symbol = "SAN", name = "Banco Santander, S.A.", exchange = "NYSE" },
                new() { symbol = "HSBC", name = "HSBC Holdings plc", exchange = "NYSE" },
                new() { symbol = "RY", name = "Royal Bank of Canada", exchange = "NYSE" },
                new() { symbol = "TD", name = "The Toronto-Dominion Bank", exchange = "NYSE" },
                new() { symbol = "BMO", name = "Bank of Montreal", exchange = "NYSE" },
                new() { symbol = "BNS", name = "The Bank of Nova Scotia", exchange = "NYSE" },
                new() { symbol = "CM", name = "Canadian Imperial Bank of Commerce", exchange = "NYSE" },
                new() { symbol = "ING", name = "ING Groep N.V.", exchange = "NYSE" },
                // Exchanges, ratings & payments data
                new() { symbol = "MKTX", name = "MarketAxess Holdings Inc.", exchange = "NASDAQ" },
                new() { symbol = "ICE", name = "Intercontinental Exchange, Inc.", exchange = "NYSE" },
                new() { symbol = "CME", name = "CME Group Inc.", exchange = "NASDAQ" },
                new() { symbol = "NDAQ", name = "Nasdaq, Inc.", exchange = "NASDAQ" },
                new() { symbol = "TW", name = "Tradeweb Markets Inc.", exchange = "NASDAQ" },
                new() { symbol = "CBOE", name = "Cboe Global Markets, Inc.", exchange = "CBOE" },
                new() { symbol = "MCO", name = "Moody's Corporation", exchange = "NYSE" },
                new() { symbol = "SPGI", name = "S&P Global Inc.", exchange = "NYSE" },
                new() { symbol = "FICO", name = "Fair Isaac Corporation", exchange = "NYSE" },
                new() { symbol = "EFX", name = "Equifax Inc.", exchange = "NYSE" },
                new() { symbol = "TRU", name = "TransUnion", exchange = "NYSE" },
                // Insurance
                new() { symbol = "ERIE", name = "Erie Indemnity Company", exchange = "NASDAQ" },
                new() { symbol = "PGR", name = "The Progressive Corporation", exchange = "NYSE" },
                new() { symbol = "ALL", name = "The Allstate Corporation", exchange = "NYSE" },
                new() { symbol = "CB", name = "Chubb Limited", exchange = "NYSE" },
                new() { symbol = "TRV", name = "The Travelers Companies, Inc.", exchange = "NYSE" },
                new() { symbol = "AIG", name = "American International Group, Inc.", exchange = "NYSE" },
                new() { symbol = "MET", name = "MetLife, Inc.", exchange = "NYSE" },
                new() { symbol = "PRU", name = "Prudential Financial, Inc.", exchange = "NYSE" },
                new() { symbol = "LNC", name = "Lincoln National Corporation", exchange = "NYSE" },
                new() { symbol = "AFL", name = "Aflac Incorporated", exchange = "NYSE" },
                new() { symbol = "PFG", name = "Principal Financial Group, Inc.", exchange = "NASDAQ" },
                new() { symbol = "GL", name = "Globe Life Inc.", exchange = "NYSE" },
                new() { symbol = "UNM", name = "Unum Group", exchange = "NYSE" },
                new() { symbol = "AIZ", name = "Assurant, Inc.", exchange = "NYSE" },
                new() { symbol = "AJG", name = "Arthur J. Gallagher & Co.", exchange = "NYSE" },
                new() { symbol = "BRO", name = "Brown & Brown, Inc.", exchange = "NYSE" },
                new() { symbol = "MMC", name = "Marsh & McLennan Companies, Inc.", exchange = "NYSE" },
                new() { symbol = "AON", name = "Aon plc", exchange = "NYSE" },
                new() { symbol = "WTW", name = "Willis Towers Watson Public Limited Company", exchange = "NASDAQ" },
                new() { symbol = "RJF", name = "Raymond James Financial, Inc.", exchange = "NYSE" },
                new() { symbol = "LPLA", name = "LPL Financial Holdings Inc.", exchange = "NASDAQ" },
                new() { symbol = "AMP", name = "Ameriprise Financial, Inc.", exchange = "NYSE" },
                // Industrials
                new() { symbol = "ETN", name = "Eaton Corporation plc", exchange = "NYSE" },
                new() { symbol = "EMR", name = "Emerson Electric Co.", exchange = "NYSE" },
                new() { symbol = "PH", name = "Parker-Hannifin Corporation", exchange = "NYSE" },
                new() { symbol = "ROK", name = "Rockwell Automation, Inc.", exchange = "NYSE" },
                new() { symbol = "ITW", name = "Illinois Tool Works Inc.", exchange = "NYSE" },
                new() { symbol = "PPG", name = "PPG Industries, Inc.", exchange = "NYSE" },
                new() { symbol = "SWK", name = "Stanley Black & Decker, Inc.", exchange = "NYSE" },
                new() { symbol = "MAS", name = "Masco Corporation", exchange = "NYSE" },
                new() { symbol = "JCI", name = "Johnson Controls International plc", exchange = "NYSE" },
                new() { symbol = "CARR", name = "Carrier Global Corporation", exchange = "NYSE" },
                new() { symbol = "TDY", name = "Teledyne Technologies Incorporated", exchange = "NYSE" },
                new() { symbol = "HWM", name = "Howmet Aerospace Inc.", exchange = "NYSE" },
                new() { symbol = "HEI", name = "HEICO Corporation", exchange = "NYSE" },
                new() { symbol = "TDG", name = "TransDigm Group Incorporated", exchange = "NYSE" },
                new() { symbol = "JBLU", name = "JetBlue Airways Corporation", exchange = "NASDAQ" },
                new() { symbol = "ALK", name = "Alaska Air Group, Inc.", exchange = "NYSE" },
                new() { symbol = "XPO", name = "XPO, Inc.", exchange = "NYSE" },
                new() { symbol = "ODFL", name = "Old Dominion Freight Line, Inc.", exchange = "NASDAQ" },
                new() { symbol = "SAIA", name = "Saia, Inc.", exchange = "NASDAQ" },
                new() { symbol = "ARCB", name = "ArcBest Corporation", exchange = "NASDAQ" },
                new() { symbol = "JBHT", name = "J.B. Hunt Transport Services, Inc.", exchange = "NASDAQ" },
                new() { symbol = "KNX", name = "Knight-Swift Transportation Holdings Inc.", exchange = "NYSE" },
                new() { symbol = "WERN", name = "Werner Enterprises, Inc.", exchange = "NASDAQ" },
                new() { symbol = "LSTR", name = "Landstar System, Inc.", exchange = "NASDAQ" },
                new() { symbol = "GXO", name = "GXO Logistics, Inc.", exchange = "NYSE" },
                new() { symbol = "CHRW", name = "C.H. Robinson Worldwide, Inc.", exchange = "NASDAQ" },
                new() { symbol = "R", name = "Ryder System, Inc.", exchange = "NYSE" },
                new() { symbol = "CNI", name = "Canadian National Railway Company", exchange = "NYSE" },
                new() { symbol = "CP", name = "Canadian Pacific Kansas City Limited", exchange = "NYSE" },
                new() { symbol = "AIT", name = "Applied Industrial Technologies, Inc.", exchange = "NYSE" },
                new() { symbol = "FAST", name = "Fastenal Company", exchange = "NASDAQ" },
                new() { symbol = "GWW", name = "W.W. Grainger, Inc.", exchange = "NYSE" },
                new() { symbol = "SNA", name = "Snap-on Incorporated", exchange = "NYSE" },
                new() { symbol = "PWR", name = "Quanta Services, Inc.", exchange = "NYSE" },
                new() { symbol = "MTZ", name = "MasTec, Inc.", exchange = "NYSE" },
                new() { symbol = "DY", name = "Dycom Industries, Inc.", exchange = "NYSE" },
                new() { symbol = "EME", name = "EMCOR Group, Inc.", exchange = "NYSE" },
                new() { symbol = "FIX", name = "Comfort Systems USA, Inc.", exchange = "NYSE" },
                new() { symbol = "ACM", name = "AECOM", exchange = "NYSE" },
                new() { symbol = "J", name = "Jacobs Solutions Inc.", exchange = "NYSE" },
                new() { symbol = "BLDR", name = "Builders FirstSource, Inc.", exchange = "NYSE" },
                new() { symbol = "OC", name = "Owens Corning", exchange = "NYSE" },
                new() { symbol = "MLM", name = "Martin Marietta Materials, Inc.", exchange = "NYSE" },
                new() { symbol = "VMC", name = "Vulcan Materials Company", exchange = "NYSE" },
                new() { symbol = "EXP", name = "Eagle Materials Inc.", exchange = "NYSE" },
                new() { symbol = "SUM", name = "Summit Materials, Inc.", exchange = "NYSE" },
                new() { symbol = "CRH", name = "CRH plc", exchange = "NYSE" },
                new() { symbol = "GVA", name = "Granite Construction Incorporated", exchange = "NYSE" },
                new() { symbol = "TTEK", name = "Tetra Tech, Inc.", exchange = "NASDAQ" },
                new() { symbol = "WAB", name = "Westinghouse Air Brake Technologies Corporation", exchange = "NYSE" },
                new() { symbol = "OSK", name = "Oshkosh Corporation", exchange = "NYSE" },
                new() { symbol = "PCAR", name = "PACCAR Inc", exchange = "NASDAQ" },
                // Communication & media
                new() { symbol = "FOXA", name = "Fox Corporation Class A", exchange = "NASDAQ" },
                new() { symbol = "NWSA", name = "News Corporation Class A", exchange = "NASDAQ" },
                new() { symbol = "NWS", name = "News Corporation Class B", exchange = "NASDAQ" },
                new() { symbol = "SIX", name = "Six Flags Entertainment Corporation", exchange = "NYSE" },
                new() { symbol = "PRKS", name = "United Parks & Resorts Inc.", exchange = "NYSE" },
                new() { symbol = "IPG", name = "The Interpublic Group of Companies, Inc.", exchange = "NYSE" },
                new() { symbol = "OMC", name = "Omnicom Group Inc.", exchange = "NYSE" },
                new() { symbol = "WPP", name = "WPP plc", exchange = "NYSE" },
                new() { symbol = "MSGE", name = "Sphere Entertainment Co.", exchange = "NYSE" },
                new() { symbol = "LYV", name = "Live Nation Entertainment, Inc.", exchange = "NYSE" },
                new() { symbol = "MAT", name = "Mattel, Inc.", exchange = "NASDAQ" },
                new() { symbol = "HAS", name = "Hasbro, Inc.", exchange = "NASDAQ" },
                new() { symbol = "TKO", name = "TKO Group Holdings, Inc.", exchange = "NYSE" },
                new() { symbol = "CELH", name = "Celsius Holdings, Inc.", exchange = "NASDAQ" },
                new() { symbol = "SAM", name = "The Boston Beer Company, Inc.", exchange = "NYSE" },
                new() { symbol = "KDP", name = "Keurig Dr Pepper Inc.", exchange = "NASDAQ" },
                new() { symbol = "CCEP", name = "Coca-Cola Europacific Partners plc", exchange = "NASDAQ" },
                new() { symbol = "COTY", name = "Coty Inc.", exchange = "NYSE" },
                new() { symbol = "ELF", name = "e.l.f. Beauty, Inc.", exchange = "NYSE" },
                // REITs & real estate
                new() { symbol = "AMT", name = "American Tower Corporation", exchange = "NYSE" },
                new() { symbol = "PLD", name = "Prologis, Inc.", exchange = "NYSE" },
                new() { symbol = "EQIX", name = "Equinix, Inc.", exchange = "NASDAQ" },
                new() { symbol = "DLR", name = "Digital Realty Trust, Inc.", exchange = "NYSE" },
                new() { symbol = "CCI", name = "Crown Castle Inc.", exchange = "NYSE" },
                new() { symbol = "PSA", name = "Public Storage", exchange = "NYSE" },
                new() { symbol = "WELL", name = "Welltower Inc.", exchange = "NYSE" },
                new() { symbol = "SPG", name = "Simon Property Group, Inc.", exchange = "NYSE" },
                new() { symbol = "O", name = "Realty Income Corporation", exchange = "NYSE" },
                new() { symbol = "VICI", name = "VICI Properties Inc.", exchange = "NYSE" },
                new() { symbol = "WY", name = "Weyerhaeuser Company", exchange = "NYSE" },
                new() { symbol = "CBRE", name = "CBRE Group, Inc.", exchange = "NYSE" },
                new() { symbol = "EXR", name = "Extra Space Storage Inc.", exchange = "NYSE" },
                new() { symbol = "AVB", name = "AvalonBay Communities, Inc.", exchange = "NYSE" },
                new() { symbol = "EQR", name = "Equity Residential", exchange = "NYSE" },
                new() { symbol = "ESS", name = "Essex Property Trust, Inc.", exchange = "NYSE" },
                new() { symbol = "MAA", name = "Mid-America Apartment Communities, Inc.", exchange = "NYSE" },
                new() { symbol = "UDR", name = "UDR, Inc.", exchange = "NYSE" },
                new() { symbol = "INVH", name = "Invitation Homes Inc.", exchange = "NYSE" },
                new() { symbol = "SBAC", name = "SBA Communications Corporation", exchange = "NASDAQ" },
                new() { symbol = "IRM", name = "Iron Mountain Incorporated", exchange = "NYSE" },
                new() { symbol = "VTR", name = "Ventas, Inc.", exchange = "NYSE" },
                new() { symbol = "DOC", name = "Healthpeak Properties, Inc.", exchange = "NYSE" },
                new() { symbol = "KIM", name = "Kimco Realty Corporation", exchange = "NYSE" },
            };
    }
}
