using System.Collections.Generic;
using System.Linq;
using api.Dtos.Stock;

namespace StockReview.Services
{
    // Curated index of well-known tickers backing the live-market search.
    // FMP's /stable/search and /stable/symbol/available-list endpoints are
    // paid-tier and return [] on the free key, so name search runs against
    // this bundled list instead (in-memory, no rate-limit cost). Tickers NOT
    // listed here can still be added via POST /api/stock/from-live, which
    // validates the exact symbol against FMP's free quote endpoint.
    //
    // The search universe is LargeCap (this file) + PopularStocksMidCap;
    // together they cover the existing database symbols plus a few hundred
    // well-known mid-caps.
    public static class PopularStocks
    {
        private static readonly IReadOnlyList<FMPStockSearchResult> LargeCap =
            new List<FMPStockSearchResult>
            {
                // Technology
                new() { symbol = "AAPL", name = "Apple Inc.", exchange = "NASDAQ" },
                new() { symbol = "MSFT", name = "Microsoft Corporation", exchange = "NASDAQ" },
                new() { symbol = "GOOGL", name = "Alphabet Inc. Class A", exchange = "NASDAQ" },
                new() { symbol = "GOOG", name = "Alphabet Inc. Class C", exchange = "NASDAQ" },
                new() { symbol = "AMZN", name = "Amazon.com Inc.", exchange = "NASDAQ" },
                new() { symbol = "META", name = "Meta Platforms Inc.", exchange = "NASDAQ" },
                new() { symbol = "NVDA", name = "NVIDIA Corporation", exchange = "NASDAQ" },
                new() { symbol = "AMD", name = "Advanced Micro Devices Inc.", exchange = "NASDAQ" },
                new() { symbol = "INTC", name = "Intel Corporation", exchange = "NASDAQ" },
                new() { symbol = "ORCL", name = "Oracle Corporation", exchange = "NYSE" },
                new() { symbol = "CRM", name = "Salesforce Inc.", exchange = "NYSE" },
                new() { symbol = "IBM", name = "International Business Machines", exchange = "NYSE" },
                new() { symbol = "CSCO", name = "Cisco Systems Inc.", exchange = "NASDAQ" },
                new() { symbol = "QCOM", name = "Qualcomm Inc.", exchange = "NASDAQ" },
                new() { symbol = "TXN", name = "Texas Instruments Inc.", exchange = "NASDAQ" },
                new() { symbol = "ADBE", name = "Adobe Inc.", exchange = "NASDAQ" },
                new() { symbol = "NFLX", name = "Netflix Inc.", exchange = "NASDAQ" },
                new() { symbol = "NOW", name = "ServiceNow Inc.", exchange = "NYSE" },
                new() { symbol = "ACN", name = "Accenture plc", exchange = "NYSE" },
                new() { symbol = "MU", name = "Micron Technology Inc.", exchange = "NASDAQ" },
                new() { symbol = "AVGO", name = "Broadcom Inc.", exchange = "NASDAQ" },
                new() { symbol = "INTU", name = "Intuit Inc.", exchange = "NASDAQ" },
                new() { symbol = "ADP", name = "Automatic Data Processing", exchange = "NASDAQ" },
                new() { symbol = "AMAT", name = "Applied Materials Inc.", exchange = "NASDAQ" },
                new() { symbol = "LRCX", name = "Lam Research Corporation", exchange = "NASDAQ" },
                new() { symbol = "KLAC", name = "KLA Corporation", exchange = "NASDAQ" },
                new() { symbol = "SNPS", name = "Synopsys Inc.", exchange = "NASDAQ" },
                new() { symbol = "CDNS", name = "Cadence Design Systems Inc.", exchange = "NASDAQ" },
                new() { symbol = "PANW", name = "Palo Alto Networks Inc.", exchange = "NASDAQ" },
                new() { symbol = "CRWD", name = "CrowdStrike Holdings Inc.", exchange = "NASDAQ" },
                new() { symbol = "ZS", name = "Zscaler Inc.", exchange = "NASDAQ" },
                new() { symbol = "NET", name = "Cloudflare Inc.", exchange = "NYSE" },
                new() { symbol = "DDOG", name = "Datadog Inc.", exchange = "NASDAQ" },
                new() { symbol = "SHOP", name = "Shopify Inc.", exchange = "NYSE" },
                new() { symbol = "SQ", name = "Block Inc.", exchange = "NYSE" },
                new() { symbol = "PYPL", name = "PayPal Holdings Inc.", exchange = "NASDAQ" },
                new() { symbol = "V", name = "Visa Inc.", exchange = "NYSE" },
                new() { symbol = "MA", name = "Mastercard Inc.", exchange = "NYSE" },
                new() { symbol = "FISV", name = "Fiserv Inc.", exchange = "NYSE" },
                new() { symbol = "GPN", name = "Global Payments Inc.", exchange = "NYSE" },
                new() { symbol = "COIN", name = "Coinbase Global Inc.", exchange = "NASDAQ" },
                new() { symbol = "PLTR", name = "Palantir Technologies Inc.", exchange = "NYSE" },
                new() { symbol = "SNOW", name = "Snowflake Inc.", exchange = "NYSE" },
                new() { symbol = "UBER", name = "Uber Technologies Inc.", exchange = "NYSE" },
                new() { symbol = "LYFT", name = "Lyft Inc.", exchange = "NASDAQ" },
                new() { symbol = "ABNB", name = "Airbnb Inc.", exchange = "NASDAQ" },
                new() { symbol = "DASH", name = "DoorDash Inc.", exchange = "NASDAQ" },
                new() { symbol = "RIVN", name = "Rivian Automotive Inc.", exchange = "NASDAQ" },
                new() { symbol = "LCID", name = "Lucid Group Inc.", exchange = "NASDAQ" },
                // Automotive
                new() { symbol = "TSLA", name = "Tesla Inc.", exchange = "NASDAQ" },
                new() { symbol = "GM", name = "General Motors Company", exchange = "NYSE" },
                new() { symbol = "F", name = "Ford Motor Company", exchange = "NYSE" },
                new() { symbol = "TM", name = "Toyota Motor Corporation", exchange = "NYSE" },
                new() { symbol = "RACE", name = "Ferrari N.V.", exchange = "NYSE" },
                new() { symbol = "STLA", name = "Stellantis N.V.", exchange = "NYSE" },
                new() { symbol = "HMC", name = "Honda Motor Co. Ltd.", exchange = "NYSE" },
                new() { symbol = "NIO", name = "NIO Inc.", exchange = "NYSE" },
                new() { symbol = "XPEV", name = "XPeng Inc.", exchange = "NYSE" },
                // Finance
                new() { symbol = "JPM", name = "JPMorgan Chase & Co.", exchange = "NYSE" },
                new() { symbol = "BAC", name = "Bank of America Corporation", exchange = "NYSE" },
                new() { symbol = "WFC", name = "Wells Fargo & Company", exchange = "NYSE" },
                new() { symbol = "C", name = "Citigroup Inc.", exchange = "NYSE" },
                new() { symbol = "GS", name = "Goldman Sachs Group Inc.", exchange = "NYSE" },
                new() { symbol = "MS", name = "Morgan Stanley", exchange = "NYSE" },
                new() { symbol = "USB", name = "U.S. Bancorp", exchange = "NYSE" },
                new() { symbol = "PNC", name = "PNC Financial Services Group", exchange = "NYSE" },
                new() { symbol = "SCHW", name = "Charles Schwab Corporation", exchange = "NYSE" },
                new() { symbol = "BLK", name = "BlackRock Inc.", exchange = "NYSE" },
                new() { symbol = "BRK.B", name = "Berkshire Hathaway Inc. Class B", exchange = "NYSE" },
                new() { symbol = "AXP", name = "American Express Company", exchange = "NYSE" },
                new() { symbol = "COF", name = "Capital One Financial Corporation", exchange = "NYSE" },
                new() { symbol = "ALLY", name = "Ally Financial Inc.", exchange = "NYSE" },
                new() { symbol = "HOOD", name = "Robinhood Markets Inc.", exchange = "NASDAQ" },
                new() { symbol = "SOFI", name = "SoFi Technologies Inc.", exchange = "NASDAQ" },
                // Energy
                new() { symbol = "XOM", name = "Exxon Mobil Corporation", exchange = "NYSE" },
                new() { symbol = "CVX", name = "Chevron Corporation", exchange = "NYSE" },
                new() { symbol = "COP", name = "ConocoPhillips", exchange = "NYSE" },
                new() { symbol = "SLB", name = "Schlumberger Limited", exchange = "NYSE" },
                new() { symbol = "OXY", name = "Occidental Petroleum Corporation", exchange = "NYSE" },
                new() { symbol = "VLO", name = "Valero Energy Corporation", exchange = "NYSE" },
                new() { symbol = "MPC", name = "Marathon Petroleum Corporation", exchange = "NYSE" },
                new() { symbol = "PSX", name = "Phillips 66", exchange = "NYSE" },
                new() { symbol = "BP", name = "BP p.l.c.", exchange = "NYSE" },
                new() { symbol = "SHEL", name = "Shell plc", exchange = "NYSE" },
                new() { symbol = "TTE", name = "TotalEnergies SE", exchange = "NYSE" },
                new() { symbol = "EQNR", name = "Equinor ASA", exchange = "NYSE" },
                // Healthcare
                new() { symbol = "UNH", name = "UnitedHealth Group Inc.", exchange = "NYSE" },
                new() { symbol = "JNJ", name = "Johnson & Johnson", exchange = "NYSE" },
                new() { symbol = "PFE", name = "Pfizer Inc.", exchange = "NYSE" },
                new() { symbol = "MRK", name = "Merck & Co. Inc.", exchange = "NYSE" },
                new() { symbol = "ABBV", name = "AbbVie Inc.", exchange = "NYSE" },
                new() { symbol = "LLY", name = "Eli Lilly and Company", exchange = "NYSE" },
                new() { symbol = "TMO", name = "Thermo Fisher Scientific Inc.", exchange = "NYSE" },
                new() { symbol = "ABT", name = "Abbott Laboratories", exchange = "NYSE" },
                new() { symbol = "MDT", name = "Medtronic plc", exchange = "NYSE" },
                new() { symbol = "BMY", name = "Bristol-Myers Squibb Company", exchange = "NYSE" },
                new() { symbol = "AMGN", name = "Amgen Inc.", exchange = "NASDAQ" },
                new() { symbol = "GILD", name = "Gilead Sciences Inc.", exchange = "NASDAQ" },
                new() { symbol = "CVS", name = "CVS Health Corporation", exchange = "NYSE" },
                new() { symbol = "HUM", name = "Humana Inc.", exchange = "NYSE" },
                new() { symbol = "CI", name = "The Cigna Group", exchange = "NYSE" },
                new() { symbol = "ELV", name = "Elevance Health Inc.", exchange = "NYSE" },
                new() { symbol = "DHR", name = "Danaher Corporation", exchange = "NYSE" },
                new() { symbol = "ISRG", name = "Intuitive Surgical Inc.", exchange = "NASDAQ" },
                new() { symbol = "BSX", name = "Boston Scientific Corporation", exchange = "NYSE" },
                new() { symbol = "SYK", name = "Stryker Corporation", exchange = "NYSE" },
                new() { symbol = "ZTS", name = "Zoetis Inc.", exchange = "NYSE" },
                new() { symbol = "REGN", name = "Regeneron Pharmaceuticals Inc.", exchange = "NASDAQ" },
                new() { symbol = "VRTX", name = "Vertex Pharmaceuticals Inc.", exchange = "NASDAQ" },
                new() { symbol = "MRNA", name = "Moderna Inc.", exchange = "NASDAQ" },
                new() { symbol = "BNTX", name = "BioNTech SE", exchange = "NASDAQ" },
                // Consumer staples & discretionary
                new() { symbol = "WMT", name = "Walmart Inc.", exchange = "NYSE" },
                new() { symbol = "COST", name = "Costco Wholesale Corporation", exchange = "NASDAQ" },
                new() { symbol = "TGT", name = "Target Corporation", exchange = "NYSE" },
                new() { symbol = "HD", name = "Home Depot Inc.", exchange = "NYSE" },
                new() { symbol = "LOW", name = "Lowe's Companies Inc.", exchange = "NYSE" },
                new() { symbol = "NKE", name = "Nike Inc.", exchange = "NYSE" },
                new() { symbol = "SBUX", name = "Starbucks Corporation", exchange = "NASDAQ" },
                new() { symbol = "MCD", name = "McDonald's Corporation", exchange = "NYSE" },
                new() { symbol = "YUM", name = "Yum! Brands Inc.", exchange = "NYSE" },
                new() { symbol = "CMG", name = "Chipotle Mexican Grill Inc.", exchange = "NYSE" },
                new() { symbol = "DRI", name = "Darden Restaurants Inc.", exchange = "NYSE" },
                new() { symbol = "KO", name = "Coca-Cola Company", exchange = "NYSE" },
                new() { symbol = "PEP", name = "PepsiCo Inc.", exchange = "NASDAQ" },
                new() { symbol = "PG", name = "Procter & Gamble Company", exchange = "NYSE" },
                new() { symbol = "CL", name = "Colgate-Palmolive Company", exchange = "NYSE" },
                new() { symbol = "KMB", name = "Kimberly-Clark Corporation", exchange = "NYSE" },
                new() { symbol = "GIS", name = "General Mills Inc.", exchange = "NYSE" },
                new() { symbol = "MDLZ", name = "Mondelez International Inc.", exchange = "NASDAQ" },
                new() { symbol = "HSY", name = "The Hershey Company", exchange = "NYSE" },
                new() { symbol = "UL", name = "Unilever plc", exchange = "NYSE" },
                new() { symbol = "PM", name = "Philip Morris International Inc.", exchange = "NYSE" },
                new() { symbol = "MO", name = "Altria Group Inc.", exchange = "NYSE" },
                new() { symbol = "STZ", name = "Constellation Brands Inc.", exchange = "NYSE" },
                new() { symbol = "EL", name = "Estée Lauder Companies Inc.", exchange = "NYSE" },
                new() { symbol = "TPR", name = "Tapestry Inc.", exchange = "NYSE" },
                new() { symbol = "TJX", name = "TJX Companies Inc.", exchange = "NYSE" },
                new() { symbol = "ROST", name = "Ross Stores Inc.", exchange = "NASDAQ" },
                new() { symbol = "DG", name = "Dollar General Corporation", exchange = "NYSE" },
                new() { symbol = "DLTR", name = "Dollar Tree Inc.", exchange = "NASDAQ" },
                new() { symbol = "CHWY", name = "Chewy Inc.", exchange = "NYSE" },
                new() { symbol = "ETSY", name = "Etsy Inc.", exchange = "NASDAQ" },
                new() { symbol = "EBAY", name = "eBay Inc.", exchange = "NASDAQ" },
                new() { symbol = "MELI", name = "MercadoLibre Inc.", exchange = "NASDAQ" },
                new() { symbol = "SE", name = "Sea Limited", exchange = "NYSE" },
                new() { symbol = "JD", name = "JD.com Inc.", exchange = "NASDAQ" },
                new() { symbol = "BABA", name = "Alibaba Group Holding Limited", exchange = "NYSE" },
                new() { symbol = "PDD", name = "PDD Holdings Inc.", exchange = "NASDAQ" },
                // Communication services
                new() { symbol = "T", name = "AT&T Inc.", exchange = "NYSE" },
                new() { symbol = "VZ", name = "Verizon Communications Inc.", exchange = "NYSE" },
                new() { symbol = "TMUS", name = "T-Mobile US Inc.", exchange = "NASDAQ" },
                new() { symbol = "DIS", name = "Walt Disney Company", exchange = "NYSE" },
                new() { symbol = "CMCSA", name = "Comcast Corporation", exchange = "NASDAQ" },
                new() { symbol = "CHTR", name = "Charter Communications Inc.", exchange = "NASDAQ" },
                new() { symbol = "WBD", name = "Warner Bros. Discovery Inc.", exchange = "NASDAQ" },
                new() { symbol = "PARA", name = "Paramount Global", exchange = "NASDAQ" },
                new() { symbol = "NYT", name = "New York Times Company", exchange = "NYSE" },
                new() { symbol = "SPOT", name = "Spotify Technology S.A.", exchange = "NYSE" },
                // Industrials & transportation
                new() { symbol = "BA", name = "Boeing Company", exchange = "NYSE" },
                new() { symbol = "LMT", name = "Lockheed Martin Corporation", exchange = "NYSE" },
                new() { symbol = "RTX", name = "RTX Corporation", exchange = "NYSE" },
                new() { symbol = "NOC", name = "Northrop Grumman Corporation", exchange = "NYSE" },
                new() { symbol = "GD", name = "General Dynamics Corporation", exchange = "NYSE" },
                new() { symbol = "CAT", name = "Caterpillar Inc.", exchange = "NYSE" },
                new() { symbol = "DE", name = "Deere & Company", exchange = "NYSE" },
                new() { symbol = "GE", name = "GE Aerospace", exchange = "NYSE" },
                new() { symbol = "HON", name = "Honeywell International Inc.", exchange = "NASDAQ" },
                new() { symbol = "MMM", name = "3M Company", exchange = "NYSE" },
                new() { symbol = "UPS", name = "United Parcel Service Inc.", exchange = "NYSE" },
                new() { symbol = "FDX", name = "FedEx Corporation", exchange = "NYSE" },
                new() { symbol = "CSX", name = "CSX Corporation", exchange = "NASDAQ" },
                new() { symbol = "NSC", name = "Norfolk Southern Corporation", exchange = "NYSE" },
                new() { symbol = "UNP", name = "Union Pacific Corporation", exchange = "NYSE" },
                new() { symbol = "DAL", name = "Delta Air Lines Inc.", exchange = "NYSE" },
                new() { symbol = "AAL", name = "American Airlines Group Inc.", exchange = "NASDAQ" },
                new() { symbol = "UAL", name = "United Airlines Holdings Inc.", exchange = "NASDAQ" },
                new() { symbol = "LUV", name = "Southwest Airlines Co.", exchange = "NYSE" },
                new() { symbol = "RYAAY", name = "Ryanair Holdings plc", exchange = "NASDAQ" },
                // Materials & misc
                new() { symbol = "LIN", name = "Linde plc", exchange = "NYSE" },
                new() { symbol = "SHW", name = "Sherwin-Williams Company", exchange = "NYSE" },
                new() { symbol = "APD", name = "Air Products and Chemicals Inc.", exchange = "NYSE" },
                new() { symbol = "DOW", name = "Dow Inc.", exchange = "NYSE" },
                new() { symbol = "DD", name = "DuPont de Nemours Inc.", exchange = "NYSE" },
                new() { symbol = "NEM", name = "Newmont Corporation", exchange = "NYSE" },
                new() { symbol = "FCX", name = "Freeport-McMoRan Inc.", exchange = "NYSE" },
                new() { symbol = "VALE", name = "Vale S.A.", exchange = "NYSE" },
                new() { symbol = "BHP", name = "BHP Group Limited", exchange = "NYSE" },
            };

        // Combined search universe: large caps + curated mid caps.
        public static readonly IReadOnlyList<FMPStockSearchResult> All =
            LargeCap.Concat(PopularStocksMidCap.All).ToList();
    }
}
